### ISSUE TITLE
sirajcoin-node giving error

### ISSUE THREAD

**Issue by ravindrabarthwal** [llSourcell/sirajcoin#11]
Hello,

I am using node js v7.10+ . I haven't given you my validator key and IP. I am getting the error below.

```
/usr/lib/node_modules/sirajcoin/app/index.js:19
    ...opts
    ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/sirajcoin/bin/node.js:3:15)

```

**Comment by ande765a** [comment]
I think you have to update Node.js to version 8 or higher for Node to support the spread operator (...) which is causing you the error.

**Comment by ravindrabarthwal** [comment]
I have upgraded to nodejs v8+ . I'm not getting any error but it's not working either, it's stuck on
**starting node...**

**Comment by ande765a** [comment]
@ravindrabarthwal  Did you remember to copy your private key to privkey.json in the current working directory before running `sirajcoin-node` ? 
Also, for me it took a little while before the node connected.

**Comment by ravindrabarthwal** [comment]
@ande765a Yup! I have privkey.json file in the validator directory from where I am executing the command. Can you tell me from where to generate validator key?

**Comment by ravindrabarthwal** [comment]
By the way, I haven't submitted my IP address and validator public key with anyone.
