### ISSUE TITLE
Not compatible with latest nodejs 9.4.0

### ISSUE THREAD

**Issue by matiwinnetou** [llSourcell/sirajcoin#14]
[mati@wit .bin]$ ./sirajcoin
```
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/home/mati/siraj/node_modules/ed25519-supercop/build/Release/supercop.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mati/siraj/node_modules/ed25519-supercop/index.js:1:78)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```
```
[mati@wit ~]$ node -v
v9.4.0
```

**Comment by matiwinnetou** [comment]
It seems to work fine using lts/carbon via nvm

**Comment by danielsan** [comment]
You can try these steps:
```bash
git clone git@github.com:llSourcell/sirajcoin.git
cd sirajcoin/
npm i -g .
sirajcoin balance
```

**Comment by mappum** [comment]
Version 1.0.7 of sirajcoin now makes the problematic `ed25519-supercop` module an optional dependency, so this should fix your problems.

Please try installing this version with:
```bash
npm i -g sirajcoin@1.0.7
```

You may reopen the issue if you still have problems.
