### ISSUE TITLE
Install SirajCoin: leveldb outputs error libtool: unrecognized option `-static'

### ISSUE THREAD

**Issue by neoneye** [llSourcell/sirajcoin#16]
Looks like a fun project.

I did the following:

1. I was unable to install sirajcoin in first attempt.
2. So I went on to updating npm.
3. Uninstalling sarajcoin.
4. Installing sarajcoin... BOOM leveldb error.

```
PROMPT> npm cache clean -f
npm WARN using --force I sure hope you know what you are doing.


PROMPT> npm install -g n
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
+ n@2.1.8
added 1 package in 0.843s


PROMPT> sudo n stable
Password:

     install : node-v9.4.0
       mkdir : /usr/local/n/versions/node/9.4.0
       fetch : https://nodejs.org/dist/v9.4.0/node-v9.4.0-darwin-x64.tar.gz
######################################################################## 100.0%
   installed : v9.4.0


PROMPT> npm uninstall -g sirajcoin
removed 685 packages in 3.094s


PROMPT> npm install -g sirajcoin
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/usr/local/bin/sirajcoin -> /usr/local/lib/node_modules/sirajcoin/bin/wallet.js
/usr/local/bin/sirajcoin-node -> /usr/local/lib/node_modules/sirajcoin/bin/node.js

> ed25519-supercop@1.0.2 install /usr/local/lib/node_modules/sirajcoin/node_modules/ed25519-supercop
> node-gyp rebuild

  CXX(target) Release/obj.target/supercop/supercop.o
  CC(target) Release/obj.target/supercop/vendor/ed25519/src/add_scalar.o
  CC(target) Release/obj.target/supercop/vendor/ed25519/src/fe.o
  CC(target) Release/obj.target/supercop/vendor/ed25519/src/ge.o
  CC(target) Release/obj.target/supercop/vendor/ed25519/src/key_exchange.o
  CC(target) Release/obj.target/supercop/vendor/ed25519/src/keypair.o
  CC(target) Release/obj.target/supercop/vendor/ed25519/src/sc.o
  CC(target) Release/obj.target/supercop/vendor/ed25519/src/seed.o
  CC(target) Release/obj.target/supercop/vendor/ed25519/src/sha512.o
  CC(target) Release/obj.target/supercop/vendor/ed25519/src/sign.o
  CC(target) Release/obj.target/supercop/vendor/ed25519/src/verify.o
  SOLINK_MODULE(target) Release/supercop.node

> fsevents@1.1.3 install /usr/local/lib/node_modules/sirajcoin/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/sirajcoin/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote

> secp256k1@3.4.0 install /usr/local/lib/node_modules/sirajcoin/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.4.0 rebuild /usr/local/lib/node_modules/sirajcoin/node_modules/secp256k1
> node-gyp rebuild

  CXX(target) Release/obj.target/secp256k1/src/addon.o
  CXX(target) Release/obj.target/secp256k1/src/privatekey.o
  CXX(target) Release/obj.target/secp256k1/src/publickey.o
  CXX(target) Release/obj.target/secp256k1/src/signature.o
  CXX(target) Release/obj.target/secp256k1/src/ecdsa.o
  CXX(target) Release/obj.target/secp256k1/src/ecdh.o
In file included from ../src/ecdh.cc:5:
In file included from ../src/secp256k1-src/src/field_impl.h:19:
../src/secp256k1-src/src/field_5x52_impl.h:267:12: warning: unused function 'secp256k1_fe_cmp_var' [-Wunused-function]
static int secp256k1_fe_cmp_var(const secp256k1_fe *a, const secp256k1_fe *b) {
           ^
In file included from ../src/ecdh.cc:7:
../src/secp256k1-src/src/group_impl.h:287:12: warning: unused function 'secp256k1_ge_is_valid_var' [-Wunused-function]
static int secp256k1_ge_is_valid_var(const secp256k1_ge *a) {
           ^
../src/secp256k1-src/src/group_impl.h:246:12: warning: unused function 'secp256k1_gej_eq_x_var' [-Wunused-function]
static int secp256k1_gej_eq_x_var(const secp256k1_fe *x, const secp256k1_gej *a) {
           ^
../src/secp256k1-src/src/group_impl.h:686:12: warning: unused function 'secp256k1_gej_has_quad_y_var' [-Wunused-function]
static int secp256k1_gej_has_quad_y_var(const secp256k1_gej *a) {
           ^
In file included from ../src/ecdh.cc:6:
../src/secp256k1-src/src/scalar_impl.h:225:13: warning: unused function 'secp256k1_scalar_inverse_var' [-Wunused-function]
static void secp256k1_scalar_inverse_var(secp256k1_scalar *r, const secp256k1_scalar *x) {
            ^
In file included from ../src/ecdh.cc:7:
../src/secp256k1-src/src/group_impl.h:113:13: warning: unused function 'secp256k1_ge_set_gej_var' [-Wunused-function]
static void secp256k1_ge_set_gej_var(secp256k1_ge *r, secp256k1_gej *a) {
            ^
../src/secp256k1-src/src/group_impl.h:267:12: warning: unused function 'secp256k1_gej_is_valid_var' [-Wunused-function]
static int secp256k1_gej_is_valid_var(const secp256k1_gej *a) {
           ^
In file included from ../src/ecdh.cc:8:
In file included from ../src/secp256k1-src/src/ecmult_const_impl.h:13:
../src/secp256k1-src/src/ecmult_impl.h:164:13: warning: unused function 'secp256k1_ecmult_context_build' [-Wunused-function]
static void secp256k1_ecmult_context_build(secp256k1_ecmult_context *ctx, const secp256k1_callback *cb) {
            ^
../src/secp256k1-src/src/ecmult_impl.h:196:13: warning: unused function 'secp256k1_ecmult_context_clone' [-Wunused-function]
static void secp256k1_ecmult_context_clone(secp256k1_ecmult_context *dst,
            ^
../src/secp256k1-src/src/ecmult_impl.h:220:13: warning: unused function 'secp256k1_ecmult_context_clear' [-Wunused-function]
static void secp256k1_ecmult_context_clear(secp256k1_ecmult_context *ctx) {
            ^
../src/secp256k1-src/src/ecmult_impl.h:216:12: warning: unused function 'secp256k1_ecmult_context_is_built' [-Wunused-function]
static int secp256k1_ecmult_context_is_built(const secp256k1_ecmult_context *ctx) {
           ^
../src/secp256k1-src/src/ecmult_impl.h:286:13: warning: unused function 'secp256k1_ecmult' [-Wunused-function]
static void secp256k1_ecmult(const secp256k1_ecmult_context *ctx, secp256k1_gej *r, const secp256k1_gej *a, const secp256k1_scalar *na, const secp256k1_scalar *ng) {
            ^
In file included from ../src/ecdh.cc:9:
../src/secp256k1-src/src/ecmult_gen_impl.h:17:13: warning: unused function 'secp256k1_ecmult_gen_context_init' [-Wunused-function]
static void secp256k1_ecmult_gen_context_init(secp256k1_ecmult_gen_context *ctx) {
            ^
../src/secp256k1-src/src/ecmult_gen_impl.h:21:13: warning: unused function 'secp256k1_ecmult_gen_context_build' [-Wunused-function]
static void secp256k1_ecmult_gen_context_build(secp256k1_ecmult_gen_context *ctx, const secp256k1_callback* cb) {
            ^
../src/secp256k1-src/src/ecmult_gen_impl.h:98:13: warning: unused function 'secp256k1_ecmult_gen_context_clone' [-Wunused-function]
static void secp256k1_ecmult_gen_context_clone(secp256k1_ecmult_gen_context *dst,
            ^
../src/secp256k1-src/src/ecmult_gen_impl.h:115:13: warning: unused function 'secp256k1_ecmult_gen_context_clear' [-Wunused-function]
static void secp256k1_ecmult_gen_context_clear(secp256k1_ecmult_gen_context *ctx) {
            ^
../src/secp256k1-src/src/ecmult_gen_impl.h:94:12: warning: unused function 'secp256k1_ecmult_gen_context_is_built' [-Wunused-function]
static int secp256k1_ecmult_gen_context_is_built(const secp256k1_ecmult_gen_context* ctx) {
           ^
../src/ecdh.cc:30:33: warning: unused variable 'default_illegal_callback' [-Wunused-const-variable]
static const secp256k1_callback default_illegal_callback = {
                                ^
../src/ecdh.cc:41:33: warning: unused variable 'default_error_callback' [-Wunused-const-variable]
static const secp256k1_callback default_error_callback = {
                                ^
19 warnings generated.
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/src/secp256k1.o
In file included from ../src/secp256k1-src/src/secp256k1.c:13:
../src/secp256k1-src/src/group_impl.h:686:12: warning: unused function 'secp256k1_gej_has_quad_y_var' [-Wunused-function]
static int secp256k1_gej_has_quad_y_var(const secp256k1_gej *a) {
           ^
../src/secp256k1-src/src/group_impl.h:267:12: warning: unused function 'secp256k1_gej_is_valid_var' [-Wunused-function]
static int secp256k1_gej_is_valid_var(const secp256k1_gej *a) {
           ^
In file included from ../src/secp256k1-src/src/secp256k1.c:15:
../src/secp256k1-src/src/ecmult_const_impl.h:122:13: warning: unused function 'secp256k1_ecmult_const' [-Wunused-function]
static void secp256k1_ecmult_const(secp256k1_gej *r, const secp256k1_ge *a, const secp256k1_scalar *scalar) {
            ^
3 warnings generated.
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_parsing.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_privatekey_parsing.o
  SOLINK_MODULE(target) Release/secp256k1.node

> utp-native@1.6.2 install /usr/local/lib/node_modules/sirajcoin/node_modules/utp-native
> node-gyp-build


> leveldown@1.7.2 install /usr/local/lib/node_modules/sirajcoin/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.4.1
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v1.7.2-node-v59-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/neoneye/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v59-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v1.7.2/leveldown-v1.7.2-node-v59-darwin-x64.tar.gz
prebuild-install http 404 https://github.com/level/leveldown/releases/download/v1.7.2/leveldown-v1.7.2-node-v59-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.4.0 runtime=node arch=x64 platform=darwin)
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix_sse.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env_posix.o
  LIBTOOL-STATIC Release/leveldb.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/leveldb.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/sirajcoin/node_modules/leveldown
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.7.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@1.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/neoneye/.npm/_logs/2018-01-20T15_41_09_348Z-debug.log


PROMPT> uname -a
Darwin abcdef.lan 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64


PROMPT> python --version
Python 2.7.13


PROMPT> gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by neoneye** [comment]
I have just now upgraded from Sierra (10.12.x) to High Sierra (10.13.2) and is getting the same failure.

```
PROMPT> python --version
Python 2.7.13

PROMPT> gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

PROMPT> node --version
v9.4.0

PROMPT> npm --version
5.6.0

PROMPT> uname -a
Darwin abcdef.lan 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
```

**Comment by mappum** [comment]
Looks like this might help you: https://stackoverflow.com/questions/38301930/libtool-unrecognized-option-static

**Comment by neoneye** [comment]
@mappum Thank you. This solved it for me.

Steps I did:
1. upgrade from Sierra to High Sierra
2. run `xcode-select --install` in order to install newest commandline tools
3. set Xcode's commandline tools in the beginning of the $PATH. Like this:
   `export PATH="$(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/bin:$PATH"`
4. `npm uninstall -g sirajcoin`
5. `npm install -g sirajcoin`

Now sirajcoin installs successfully.

I can run `sirajcoin balance`.
