### ISSUE TITLE
Lost my wallet npm error

### ISSUE THREAD

**Issue by techgeeksid** [llSourcell/sirajcoin#25]
Sirajcoin balance now I am getting error after updating to 1.0.8

**Comment by mappum** [comment]
What error output are you getting?

**Comment by techgeeksid** [comment]
Error: Could not locate the bindings file. Tried:
 → /home/ubuntu/Desktop/tt/sirajcoin-master/node_modules/leveldown/build/leveldown.node
 → /home/ubuntu/Desktop/tt/sirajcoin-master/node_modules/leveldown/build/Debug/leveldown.node
 → /home/ubuntu/Desktop/tt/sirajcoin-master/node_modules/leveldown/build/Release/leveldown.node
 → /home/ubuntu/Desktop/tt/sirajcoin-master/node_modules/leveldown/out/Debug/leveldown.node
 → /home/ubuntu/Desktop/tt/sirajcoin-master/node_modules/leveldown/Debug/leveldown.node
 → /home/ubuntu/Desktop/tt/sirajcoin-master/node_modules/leveldown/out/Release/leveldown.node
 → /home/ubuntu/Desktop/tt/sirajcoin-master/node_modules/leveldown/Release/leveldown.node
 → /home/ubuntu/Desktop/tt/sirajcoin-master/node_modules/leveldown/build/default/leveldown.node
 → /home/ubuntu/Desktop/tt/sirajcoin-master/node_modules/leveldown/compiled/9.4.0/linux/x64/leveldown.node
    at bindings (/home/ubuntu/Desktop/tt/sirajcoin-master/node_modules/leveldown/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/ubuntu/Desktop/tt/sirajcoin-master/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/Desktop/tt/sirajcoin-master/node_modules/level/level.js:1:106)

**Comment by techgeeksid** [comment]
sudo npm uninstall -g sirajcoin
 sudo npm i -g
sudo sirajcoin balance

solved the problem
