### ISSUE TITLE
Warnings in npm install and error while checking balance. Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by prathmeshpalande** [llSourcell/sirajcoin#34]
While NPM Install:

sudo npm i -g sirajcoin
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/usr/bin/sirajcoin -> /usr/lib/node_modules/sirajcoin/bin/wallet.js
/usr/bin/sirajcoin-node -> /usr/lib/node_modules/sirajcoin/bin/node.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/sirajcoin/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ sirajcoin@1.0.9
updated 1 package in 45.635s

And while "sirajcoin balance":

sirajcoin balance
/usr/lib/node_modules/sirajcoin/node_modules/supercop.js/lib.js:97
      throw ex;
      ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/sirajcoin/node_modules/leveldown/build/leveldown.node
 → /usr/lib/node_modules/sirajcoin/node_modules/leveldown/build/Debug/leveldown.node
 → /usr/lib/node_modules/sirajcoin/node_modules/leveldown/build/Release/leveldown.node
 → /usr/lib/node_modules/sirajcoin/node_modules/leveldown/out/Debug/leveldown.node
 → /usr/lib/node_modules/sirajcoin/node_modules/leveldown/Debug/leveldown.node
 → /usr/lib/node_modules/sirajcoin/node_modules/leveldown/out/Release/leveldown.node
 → /usr/lib/node_modules/sirajcoin/node_modules/leveldown/Release/leveldown.node
 → /usr/lib/node_modules/sirajcoin/node_modules/leveldown/build/default/leveldown.node
 → /usr/lib/node_modules/sirajcoin/node_modules/leveldown/compiled/8.9.4/linux/x64/leveldown.node
    at bindings (/usr/lib/node_modules/sirajcoin/node_modules/leveldown/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/lib/node_modules/sirajcoin/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/sirajcoin/node_modules/level/level.js:1:106)

**Comment by ShahZafrani** [comment]
Try reinstalling node with nvm. I had this issue as well as #22. it fixed both of them for me.

**Comment by hdon** [comment]
FYI it is [https://givan.se/do-not-sudo-npm/](not recommended to sudo npm) at all. I just learned this, and while I have some mixed feelings about it, looking through the node-gyp code suggests that for now, it's the path of least resistance.

**Comment by prathmeshpalande** [comment]
@ShahZafrani Alright. I guess that should work.

**Comment by prathmeshpalande** [comment]
@hdon It gives an insufficient permissions error without sudo. How do I give it permissions without making it sudo?

**Comment by hdon** [comment]
@prathmeshpalande install node under your unprivileged user account from the downloads available from the official nodejs website. all you need to do is extract the archive and edit your PATH variable.

I don't know if this situation has changed, but nodejs releases come way faster than distros seem to want to keep up with. For that reason, I generally recommend against using your distro's node package.
