### ISSUE TITLE
error on mac

### ISSUE THREAD

**Issue by cameronbergh** [llSourcell/sirajcoin#35]
after installing node 9.4.0

and running npm i -g sirajcoin

then

sirajcoin balance

returns:

MacBook-Pro:~ cameron$ sirajcoin balance
/usr/local/lib/node_modules/sirajcoin/bin/wallet.js:31
async function main() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by cameronbergh** [comment]
solved by doing:

sudo npm cache clean -f
sudo npm install -g n
sudo n stable

npm uninstall -g sirajcoin
npm install -g sirajcoin
