### ISSUE TITLE
Error running sirajcoin balance on v8.5

### ISSUE THREAD

**Issue by hectormenendez** [llSourcell/sirajcoin#4]
```
Generated private key, saving to "/Users/hmenendez/.sirajcoin/keys.json"
Error: Private key must be a 32-byte buffer
    at module.exports (/Users/hmenendez/.nvm/versions/node/v8.5.0/lib/node_modules/sirajcoin/client/wallet-methods.js:7:11)
    at main (/Users/hmenendez/.nvm/versions/node/v8.5.0/lib/node_modules/sirajcoin/bin/wallet.js:58:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
Connecting...
```

**Comment by mappum** [comment]
Hm, you may need to reinstall sirajcoin with `npm i -g sirajcoin@1.0.6` to make sure you're on the latest version. Let me know if that helps.

**Comment by kilianc** [comment]
```
+ sirajcoin@1.0.6
added 685 packages in 73.676s
```

same on v9.2.0

**Comment by AngeGallego** [comment]
I have a similar issue using Node v9.4.0
the error log : https://pastebin.com/AH9TuMe5

**Comment by aslafy-z** [comment]
same for me with node v9.4.0

**Comment by swapu258** [comment]
aslafy-z yup it works

**Comment by hdon** [comment]
This was a bug fixed by fbbf81aca2fc06e133ed7698f1266b98b4089d24 which did not supply the correct representation of the private key to `Wallet()` unless the key was read from disk.

This issue should be closeable @mappum

**Comment by Baifamonv** [comment]
sirajcoin balance with node v9.7.1
/usr/local/lib/node_modules/sirajcoin/node_modules/supercop.js/lib.js:97
      throw ex;
      ^

Error: connect ECONNREFUSED 159.89.152.187:46657
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1189:14)
