### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by abhijayghildyal** [llSourcell/sirajcoin#44]
When I run: `$ sirajcoin balance`

The following error occurs:
 
    /home/user.user_path/.sirajcoin/node_modules/supercop.js/lib.js:97
          throw ex;
          ^

    Error: Could not locate the bindings file. Tried:
     → /home/user_path/.sirajcoin/node_modules/leveldown/build/leveldown.node
     → /home/user_path/.sirajcoin/node_modules/leveldown/build/Debug/leveldown.node
     → /home/user_path/.sirajcoin/node_modules/leveldown/build/Release/leveldown.node
     → /home/user_path/.sirajcoin/node_modules/leveldown/out/Debug/leveldown.node
     → /home/user_path/.sirajcoin/node_modules/leveldown/Debug/leveldown.node
     → /home/user_path/.sirajcoin/node_modules/leveldown/out/Release/leveldown.node
     → /home/user_path/.sirajcoin/node_modules/leveldown/Release/leveldown.node
     → /home/user_path/.sirajcoin/node_modules/leveldown/build/default/leveldown.node
     → /home/user_path/.sirajcoin/node_modules/leveldown/compiled/9.8.0/linux/x64/leveldown.node
        at bindings (/home/user_path/.sirajcoin/node_modules/bindings/bindings.js:93:9)
        at Object.<anonymous> (/home/user_path/.sirajcoin/node_modules/leveldown/leveldown.js:4:46)
        at Module._compile (module.js:649:30)
        at Object.Module._extensions..js (module.js:660:10)
        at Module.load (module.js:561:32)
        at tryModuleLoad (module.js:501:12)
        at Function.Module._load (module.js:493:3)
        at Module.require (module.js:593:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/home/user_path/.sirajcoin/node_modules/level/level.js:1:106)
 
I am unable to understand what might be causing this error.

**Comment by emanom** [comment]
I'm experimenting the same exception when asking for the balance:
Error: connect ECONNREFUSED 165.227.25.82:46657

it used to work...
