### ISSUE TITLE
sirajcoin balance not working

### ISSUE THREAD

**Issue by collegepinger** [llSourcell/sirajcoin#5]
```
:/home/ubuntu# sirajcoin balance
module.js:557
    throw err;
    ^

Error: Cannot find module './build/Release/supercop.node'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/sirajcoin/node_modules/ed25519-supercop/index.js:1:78)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

**Comment by MichalGallovic** [comment]
Hey @collegepinger what is your node version and npm versions ?

**Comment by techgeeksid** [comment]
Same error for me 

I tried this solutions but still same error I am using Ubuntu 17.10

**Comment by MichalGallovic** [comment]
@techgeeksid checkout also #4 that may help

**Comment by HvyD** [comment]
On Ubuntu 17.10 this worked for me:
$sudo npm cache clean -f
$npm install 9.4.0
$sudo n stable
$npm use 9.4.0
$sudo npm install -g sirajcoin

**Comment by ternado** [comment]
Installing is working fine, but when I try sirajcoin balance, it threw an error as below

`.nvm/versions/node/v9.8.0/lib/node_modules/sirajcoin/node_modules/supercop.js/lib.js:97`
        throw ex;
                 ^

`Error: connect ECONNREFUSED 159.89.152.187:46657
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1170:14)`

**Comment by ternado** [comment]
@llSourcell , tried those methods mentioned below, still get this error .

Error: connect ECONNREFUSED 159.89.152.187:46657
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1170:14)
/Users/hostname/.nvm/versions/node/v9.8.0/lib/node_modules/sirajcoin/node_modules/supercop.js/lib.js:97
      throw ex;
      ^

Error: connect ECONNREFUSED 159.89.152.187:46657
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1170:14)
