### ISSUE TITLE
npm warn

### ISSUE THREAD

**Issue by techgeeksid** [llSourcell/sirajcoin#6]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/sirajcoin/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by mappum** [comment]
That's just a warning and not an error, so it's ok. :)

Did you get any error output along with this?

**Comment by 1nF0rmed** [comment]
I actually got an error.


SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
/usr/local/lib
`-- (empty)

npm WARN optional Skipping failed optional dependency /sirajcoin/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm ERR! Linux 4.13.0-26-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "sirajcoin"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! lotion@0.1.10 install: `node bin/download.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lotion@0.1.10 install script 'node bin/download.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lotion package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/download.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lotion
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lotion
npm ERR! There is likely additional logging output above.

As a follow up what versions of **npm** and **nodejs** is required to set this up?
Thank you

**Comment by mappum** [comment]
@1nF0rmed you'll need Node version 8 or higher, I'll update the README and package.json to show that.

**Comment by hdon** [comment]
@mappum my guess is you can close this issue as you addressed both in 5605a7f8d58e9cbec0df88e4888cd5e4ea0fe1f4 and 4b1249a71b9921b5055ecd6d599c052db8e5fcc8

Links to specific changes:

https://github.com/llSourcell/sirajcoin/commit/5605a7f8d58e9cbec0df88e4888cd5e4ea0fe1f4#diff-04c6e90faac2675aa89e2176d2eec7d8R14

https://github.com/llSourcell/sirajcoin/commit/4b1249a71b9921b5055ecd6d599c052db8e5fcc8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R6

You can automatically close issues from your commit message:

https://help.github.com/articles/closing-issues-using-keywords/
