### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by mappum** [llSourcell/sirajcoin#9]
Currently not working on Windows, will need to fix the underlying code in [lotion](https://github.com/keppel/lotion) and this repo.

**Comment by u0m3** [comment]
I installed it on Windows 10 64bit without problems. What issues did you encounter ?

**Comment by mappum** [comment]
I actually didn't test it, I just haven't had windows in mind when writing the code and assumed there would be issues. So the wallet is working on windows? That's great news!

I do think the full nodes are broken on windows however.

**Comment by u0m3** [comment]
Yes I forgot to mention I only installed the wallet (the `npm i -g sirajcoin`) and did not try to clone the repo and play with that.

**Comment by purvikpatel** [comment]
Error While installing the Wallet in Windows 10 using `npm i -g sirajcoin`
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
C:\Users\Purvik\AppData\Roaming\npm\sirajcoin-node -> C:\Users\Purvik\AppData\Roaming\npm\node_modules\sirajcoin\bin\node.js
C:\Users\Purvik\AppData\Roaming\npm\sirajcoin -> C:\Users\Purvik\AppData\Roaming\npm\node_modules\sirajcoin\bin\wallet.js

> secp256k1@3.4.0 install C:\Users\Purvik\AppData\Roaming\npm\node_modules\sirajcoin\node_modules\secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.4.0 rebuild C:\Users\Purvik\AppData\Roaming\npm\node_modules\sirajcoin\node_modules\secp256k1
> node-gyp rebuild


C:\Users\Purvik\AppData\Roaming\npm\node_modules\sirajcoin\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Purvik\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Purvik\AppData\Roaming\npm\node_modules\sirajcoin\node_modules\secp256k1
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Purvik\AppData\Roaming\npm-cache\_logs\2018-01-22T16_06_03_952Z-debug.log
"Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> utp-native@1.6.2 install C:\Users\Purvik\AppData\Roaming\npm\node_modules\sirajcoin\node_modules\utp-native
> node-gyp-build


> leveldown@1.7.2 install C:\Users\Purvik\AppData\Roaming\npm\node_modules\sirajcoin\node_modules\leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.4.1
prebuild-install info looking for local prebuild @ prebuilds\leveldown-v1.7.2-node-v59-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\Purvik\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v59-win32-x64.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v1.7.2/leveldown-v1.7.2-node-v59-win32-x64.tar.gz
prebuild-install http 404 https://github.com/level/leveldown/releases/download/v1.7.2/leveldown-v1.7.2-node-v59-win32-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.4.0 runtime=node arch=x64 platform=win32)

C:\Users\Purvik\AppData\Roaming\npm\node_modules\sirajcoin\node_modules\leveldown>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Purvik\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Purvik\AppData\Roaming\npm\node_modules\sirajcoin\node_modules\leveldown
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\sirajcoin\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.7.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@1.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Purvik\AppData\Roaming\npm-cache\_logs\2018-01-22T16_06_26_677Z-debug.log

**Comment by purvikpatel** [comment]
Can anyone help  me with these?

**Comment by wolfnether** [comment]
> gyp ERR! stack Error: Can't find Python executable 

did you have python3 installed?

**Comment by purvikpatel** [comment]
Yes I have installed Python 3

**Comment by wolfnether** [comment]
> C:\Users\Purvik\AppData\Local\Programs\Python\Python36-32\python.EXE

i'm not sure that is an executable, verify it

**Comment by purvikpatel** [comment]
Ok Thanks
